### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by simpsus** [teddykoker/torchsort#45]
pip install torchsort
Collecting torchsort
  Using cached torchsort-0.1.8.tar.gz (15 kB)
Requirement already satisfied: torch in ./miniconda3/envs/numerai/lib/python3.8/site-packages (from torchsort) (1.10.1)
Requirement already satisfied: typing_extensions in ./miniconda3/envs/numerai/lib/python3.8/site-packages (from torch->torchsort) (3.10.0.2)
Building wheels for collected packages: torchsort
  Building wheel for torchsort (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/gbrecht/miniconda3/envs/numerai/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ae5914wo
       cwd: /tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/
  Complete output (63 lines):
  running bdist_wheel
  /home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/torchsort
  copying torchsort/ops.py -> build/lib.linux-x86_64-3.8/torchsort
  copying torchsort/__init__.py -> build/lib.linux-x86_64-3.8/torchsort
  running egg_info
  writing torchsort.egg-info/PKG-INFO
  writing dependency_links to torchsort.egg-info/dependency_links.txt
  writing requirements to torchsort.egg-info/requires.txt
  writing top-level names to torchsort.egg-info/top_level.txt
  reading manifest file 'torchsort.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'torchsort.egg-info/SOURCES.txt'
  copying torchsort/isotonic_cpu.cpp -> build/lib.linux-x86_64-3.8/torchsort
  copying torchsort/isotonic_cuda.cu -> build/lib.linux-x86_64-3.8/torchsort
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py", line 52, in <module>
      setup(
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 390, in build_extensions
      self._check_abi()
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 761, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 294, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 254, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['which', '/home/gbrecht/miniconda3/envs/env_name/bin/x86_64-conda_cos6-linux-gnu-g++']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for torchsort
  Running setup.py clean for torchsort
Failed to build torchsort
Installing collected packages: torchsort
    Running setup.py install for torchsort ... error
    ERROR: Command errored out with exit status 1:
     command: /home/gbrecht/miniconda3/envs/numerai/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ebscxvww/install-record.txt --single-version-externally-managed --compile --install-headers /home/gbrecht/miniconda3/envs/numerai/include/python3.8/torchsort
         cwd: /tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/
    Complete output (65 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/torchsort
    copying torchsort/ops.py -> build/lib.linux-x86_64-3.8/torchsort
    copying torchsort/__init__.py -> build/lib.linux-x86_64-3.8/torchsort
    running egg_info
    writing torchsort.egg-info/PKG-INFO
    writing dependency_links to torchsort.egg-info/dependency_links.txt
    writing requirements to torchsort.egg-info/requires.txt
    writing top-level names to torchsort.egg-info/top_level.txt
    /home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    reading manifest file 'torchsort.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'torchsort.egg-info/SOURCES.txt'
    copying torchsort/isotonic_cpu.cpp -> build/lib.linux-x86_64-3.8/torchsort
    copying torchsort/isotonic_cuda.cu -> build/lib.linux-x86_64-3.8/torchsort
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py", line 52, in <module>
        setup(
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 390, in build_extensions
        self._check_abi()
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 761, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 294, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 254, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['which', '/home/gbrecht/miniconda3/envs/env_name/bin/x86_64-conda_cos6-linux-gnu-g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gbrecht/miniconda3/envs/numerai/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-13efi_54/torchsort_345be19e602e41578bf71da3cb5a3cee/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ebscxvww/install-record.txt --single-version-externally-managed --compile --install-headers /home/gbrecht/miniconda3/envs/numerai/include/python3.8/torchsort Check the logs for full command output.

**Comment by simpsus** [comment]
linux mint (ubuntu based)
torch 1.10.1 
no cuda installed or motivation to do

**Comment by teddykoker** [comment]
Hi! Do you have `g++` installed? It is necessary to build the package when you install it. You can install with:
```bash
sudo apt install g++
```
Then try to install torchsort again.

**Comment by simpsus** [comment]
Thank you very much. Not very smart of me to miss that. I was so focused on following the conda environment suggestions on the readme.md that I forgot to check that ...
